services:

  postgresql:
    image: postgres:17
    container_name: postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    volumes:
      - pg_data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432

  ingestao:
    build:
      context: .
      dockerfile: Dockerfile.python
    container_name: ingestao
    volumes:
      - ./homework/data:/data
      - ./homework/python:/app
    env_file:
      - .env
    depends_on:
      - postgresql
    # command: python ingestao_dados.py (Para fazer de forma autom√°tica)

  pgadmin:
    build:
      context: .
      dockerfile: Dockerfile.pgadmin
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    volumes:
      - ./conf/pgadmin_pass:/pgadmin4/pass
      - ./conf/pgadmin_servers.json:/pgadmin4/servers.json
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - 8080:80
    depends_on: 
      - postgresql
      
volumes:
  pg_data:
  pgadmin_data:

